In [168]:
from __future__ import print_function
from keras.preprocessing.text import text_to_word_sequence
import pandas as pd
from keras.preprocessing.text import Tokenizer
import numpy as np
from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.layers import Embedding
from keras.layers import Conv1D, GlobalMaxPooling1D

In [169]:
# Read the input dataset 
filepath_dire = {'data': './ACPD.csv'}
data_list = []
for source, filepath in filepath_dire.items():
 data = pd.read_csv(filepath, names=['sentence', 'label'], sep=',')
 data['source'] = source  # Add another column filled with the source name
 data_list.append(data)
data = pd.concat(data_list)
x= data['sentence']
y= data['label']
print(x)

#there are {5} unique classes for classification
print(np.unique(y, return_counts=True))

0      on 13th and or 14th day of January 1958, they ...
1      According to prosecution, accused 1 and 2 comm...
2      The briefly stated prosecution story is that o...
3      Sole accused in this case was sent up for tria...
4      The case of prosecution as unfolded by report ...
                             ...                        
172    instant case pertains to the abduction of PWs ...
173    Victim, aged about six years, was allegedly ki...
174    Planned kidnapping of 3 minor children aged ab...
175               Kidnapping in order to compel marriage
176       Kidnapping of two children aged 6 and 8 years 
Name: sentence, Length: 177, dtype: object
(array([302, 364, 375, 383, 390]), array([50, 22, 31, 24, 50]))


In [170]:
tk = Tokenizer(num_words= 400, filters = '!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',lower=True, split=" ")
tk.fit_on_texts(x)
x = tk.texts_to_sequences(x)
x = sequence.pad_sequences(x, maxlen=150)

print(x)

[[  0   0   0 ...   4   2 155]
 [  0   0   0 ...  37  33  91]
 [  0   0   0 ...   1   3 281]
 ...
 [  0   0   0 ... 138  22 127]
 [  0   0   0 ...   5   4 262]
 [  0   0   0 ...   2 109  62]]


In [171]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_Y = LabelEncoder()
print(y)
y = labelencoder_Y.fit_transform(y)
print(np.unique(y, return_counts=True))

0      390
1      390
2      390
3      390
4      390
      ... 
172    364
173    364
174    364
175    364
176    364
Name: label, Length: 177, dtype: int64
(array([0, 1, 2, 3, 4]), array([50, 22, 31, 24, 50]))


In [172]:
from keras import utils as np_utils
print(y)
y = np_utils.to_categorical(y, num_classes= 5)
print(y)


[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0.

In [173]:
np.random.seed(150)
indices = np.arange(len(x))
np.random.shuffle(indices)
print(x)
x = x[indices]
y = y[indices]
print(x)

[[  0   0   0 ...   4   2 155]
 [  0   0   0 ...  37  33  91]
 [  0   0   0 ...   1   3 281]
 ...
 [  0   0   0 ... 138  22 127]
 [  0   0   0 ...   5   4 262]
 [  0   0   0 ...   2 109  62]]
[[  0   0   0 ...   5   3  86]
 [  0   0   0 ...   4   1  31]
 [  0   0   0 ...   5  12  25]
 ...
 [  0   0   0 ...   2 156   2]
 [  0   0   0 ...   8  92  42]
 [  0   0   0 ...  90 105  41]]


In [174]:
index_from=4
start_char = 1
if start_char is not None:
        x = [[start_char] + [w + index_from for w in x1] for x1 in x]
elif index_from:
        x = [[w + index_from for w in x1] for x1 in x]
print(x[0])

[1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 13, 32, 5, 79, 7, 16, 93, 5, 22, 17, 5, 9, 7, 90]


In [175]:
num_words = None
if not num_words:
        num_words = max([max(x1) for x1 in x])
        
oov_char = 2
skip_top = 0
# by convention, use 2 as OOV word
# reserve 'index_from' (=3 by default) characters:
# 0 (padding), 1 (start), 2 (OOV)
if oov_char is not None:
        x = [[w if (skip_top <= w < num_words) else oov_char for w in x1] for x1 in x]
else:
        x = [[w for w in x1 if (skip_top <= w < num_words)] for x1 in x]
# split test and train data
test_split = 0.2
idx = int(len(x) * (1 - test_split))
x_train, y_train = np.array(x[:idx]), np.array(y[:idx])
x_test, y_test = np.array(x[idx:]), np.array(y[idx:])

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)
# print(y)

(141, 151)
(141, 5)
(36, 151)
(36, 5)


In [176]:
x_train = sequence.pad_sequences(x_train, maxlen=151)
x_test = sequence.pad_sequences(x_test, maxlen=151)
print('x_train shape:', x_train.shape)
print('x_test shape:', x_test.shape)

x_train shape: (141, 151)
x_test shape: (36, 151)


In [177]:
max_features = 1000
maxlen = 151
embedding_dims = 50
filters = 250
kernel_size = 3
hidden_dims = 250


# CNN with max pooling imeplementation 
print('Build model...')
model = Sequential()
# we start off with an efficient embedding layer which maps
# our vocab indices into embedding_dims dimensions
model.add(Embedding(max_features,
                    embedding_dims,
                    input_length=maxlen))
model.add(Dropout(0.4))

# we add a Convolution1D, which will learn filters
# word group filters of size filter_length:
model.add(Conv1D(filters,
                 kernel_size,
                 padding='valid',
                 activation='relu',
                 strides=1))
# we use max pooling:
model.add(GlobalMaxPooling1D())

# We add a vanilla hidden layer:
model.add(Dense(hidden_dims))
model.add(Dropout(0.4))
model.add(Activation('relu'))

# We project onto a single unit output layer, and squash it with a sigmoid:
model.add(Dense(5))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

model.fit(x_train, y_train,
          batch_size=10,
          epochs=15,
          validation_data=(x_test, y_test))
model.summary()

Build model...


/Users/himanshu/opt/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/framework/indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Train on 141 samples, validate on 36 samples
Epoch 1/15
141/141 [==============================] - 3s 18ms/step - loss: 1.5646 - accuracy: 0.2766 - val_loss: 1.6001 - val_accuracy: 0.2500
Epoch 2/15
141/141 [==============================] - 1s 6ms/step - loss: 1.5030 - accuracy: 0.3617 - val_loss: 1.6041 - val_accuracy: 0.2500
Epoch 3/15
141/141 [==============================] - 1s 6ms/step - loss: 1.4744 - accuracy: 0.3759 - val_loss: 1.6009 - val_accuracy: 0.3889
Epoch 4/15
141/141 [==============================] - 1s 6ms/step - loss: 1.4242 - accuracy: 0.4823 - val_loss: 1.6472 - val_accuracy: 0.1667
Epoch 5/15
141/141 [==============================] - 1s 6ms/step - loss: 1.3106 - accuracy: 0.5603 - val_loss: 1.4576 - val_accuracy: 0.4167
Epoch 6/15
141/141 [==============================] - 1s 7ms/step - loss: 1.2169 - accuracy: 0.5603 - val_loss: 1.3492 - val_accuracy: 0.4167
Epoch 7/15
141/141 [==============================] - 1s 7ms/step - loss: 1.0782 - accuracy: 0.5887 - 

In [178]:

print(x_train)

[[ 1  4  4 ...  9  7 90]
 [ 1  4  4 ...  8  5 35]
 [ 1  4  4 ...  9 16 29]
 ...
 [ 1  4  4 ... 10 14  9]
 [ 1  4  4 ... 65  8 89]
 [ 1  4  4 ... 53 34 95]]


In [183]:
#  code to test one sentece 
inp = ['accussed committed theft of gold ornaments','minor girl is raped by accused','Exchange of words between accused and deceased followed by infliction of single injury leading to death']
#accussed committed theft of gold ornaments
#minor girl is raped by accused
#Exchange of words between accused and deceased followed by infliction of single injury leading to death
print(inp)
inp = tk.texts_to_sequences(inp)
inp = sequence.pad_sequences(inp, maxlen=150)
index_from=4
start_char = 1
if start_char is not None:
        inp = [[start_char] + [w + index_from for w in x1] for x1 in inp]
elif index_from:
        inp = [[w + index_from for w in x1] for x1 in inp]
num_words = None
if not num_words:
        num_words = max([max(x1) for x1 in inp])
        
oov_char = 2
skip_top = 0
# by convention, use 2 as OOV word
# reserve 'index_from' (=3 by default) characters:
# 0 (padding), 1 (start), 2 (OOV)
if oov_char is not None:
        inp = [[w if (skip_top <= w < num_words) else oov_char for w in x1] for x1 in inp]
else:
        inp = [[w for w in x1 if (skip_top <= w < num_words)] for x1 in inp]
print(inp)
inp=sequence.pad_sequences(inp, maxlen=151)
print(model.predict(inp).argmax(axis=1))
print(model.predict(inp))
labelencoder_Y.classes_[model.predict(inp).argmax(axis=1)]
#improvements 
#learn on cases outputs 

['accussed committed theft of gold ornaments', 'minor girl is raped by accused', 'Exchange of words between accused and deceased followed by infliction of single injury leading to death']
[[1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 32, 105, 7, 67, 2], [1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 

array([390, 375, 302])

In [13]:
model.save('model.h5')

In [184]:
import pickle
import os
from keras.preprocessing import sequence

with open('clf.pickle', 'wb') as f:
     pickle.dump(model, f)
with open('nlpclf.pickle', 'wb') as f:
     pickle.dump(tk, f)
with open('labelencoder.pickle', 'wb') as f:
     pickle.dump(labelencoder_Y, f)
os.listdir()
['clf.pickle']
with open('clf.pickle', 'rb') as f:
    modelrr = pickle.load(f)
with open('nlpclf.pickle', 'rb') as f:
    tokenz = pickle.load(f)
with open('labelencoder.pickle', 'rb') as f:
    labelencoder = pickle.load(f)

/Users/himanshu/opt/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/framework/indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


In [185]:
inp = ['accussed committed theft of gold ornaments',
       'This witness has stated that the detenu and his associates extort money at the point of weapons from businessmen, shopkeepers and hawkers of the area; that whoever refuses to give them hapta money are threatened by them and that out of fear nobody complains against them',
       'Exchange of words between accused and deceased followed by infliction of single injury leading to death',
       'it is established that offender after kidnapping a person keeps him in detention or threatens to cause death or hurt in order to extort ransom, and communicates that demand'
      ]
#accussed raped a girl for 7 days
#accussed murdered a man
#accussed committed theft of gold ornaments
print(inp)
inp = tokenz.texts_to_sequences(inp)
inp = sequence.pad_sequences(inp, maxlen=150)
index_from=4
start_char = 1
if start_char is not None:
        inp = [[start_char] + [w + index_from for w in x1] for x1 in inp]
elif index_from:
        inp = [[w + index_from for w in x1] for x1 in inp]
num_words = None
if not num_words:
        num_words = max([max(x1) for x1 in inp])
        
oov_char = 2
skip_top = 0
# by convention, use 2 as OOV word
# reserve 'index_from' (=3 by default) characters:
# 0 (padding), 1 (start), 2 (OOV)
if oov_char is not None:
        inp = [[w if (skip_top <= w < num_words) else oov_char for w in x1] for x1 in inp]
else:
        inp = [[w for w in x1 if (skip_top <= w < num_words)] for x1 in inp]
print(inp)
inp=sequence.pad_sequences(inp, maxlen=151)
print(modelrr.predict(inp).argmax(axis=1))
labelencoder.classes_[modelrr.predict(inp).argmax(axis=1)]

['accussed committed theft of gold ornaments', 'This witness has stated that the detenu and his associates extort money at the point of weapons from businessmen, shopkeepers and hawkers of the area; that whoever refuses to give them hapta money are threatened by them and that out of fear nobody complains against them', 'Exchange of words between accused and deceased followed by infliction of single injury leading to death', 'it is established that offender after kidnapping a person keeps him in detention or threatens to cause death or hurt in order to extort ransom, and communicates that demand']
[[1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4

array([390, 383, 302, 302])

In [73]:
type(modelrr)

keras.engine.sequential.Sequential